version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://username:password@postgres:5432/axum
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    build: ./init_db
    environment:
      POSTGRES_DB: axum
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d axum"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - app_network
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge